### ISSUE TITLE
Compiling a bleeding-edge version of libnode_jll

### ISSUE THREAD

**Issue by tshort** [sunoru/NodeCall.jl#14]
I'm interested in using a recent version of Node. That's to get some bleeding edge / experimental WebAssembly support. 

How hard is it to "dev" a version of `libnode_jll` locally and update the Node version? This isn't something I expect anyone else to want, so that's why I was thinking of trying it locally.

**Comment by sunoru** [comment]
You need to call `dev_jll()` for both `libnode_jll` and `libjlnode_jll`, and compile your own version of shared library of node.

If you are using Linux/mac, you can just do  `./configure --shared && make -j` to build libnode, and then copy the output files to the `override` directory.

To build libjlnode, you can do something like [this CI script](https://github.com/sunoru/jlnode/blob/main/.github/workflows/build.yml). Basically it's setting `LD_LIBRARY_PATH` to the shared library you just built and running `npm run build`.

And note that you'd better use the node version you want to use to run `npm`.

**Comment by tshort** [comment]
Awesome. Thanks so much!

**Comment by tshort** [comment]
I gave this a try recently. I eventually gave up, but here is some progress I made:

* The `dev_jll()` calls worked great.
* Node v20.6.0 compiled fine.
* Running node within Julia failed with a `'GLIBCXX_X.X.XX' not found` error. See [here](https://juliagpu.github.io/Vulkan.jl/dev/troubleshooting/#libstdc) for how to fix that with `LD_PRELOAD`.
* Compiling [jlnode](https://github.com/sunoru/jlnode) was where I got stuck. Here were my steps to try to fix things:
  * Change the `CMakeLists.txt` to force the C++ version in GCC (`-std=c++17`).
  * Updated the node-addon to v7.
  * Commented out [this line](https://github.com/sunoru/jlnode/blob/dfddbd64366931b822b8fc1476ba990cc3aac960/src/jlnode/instance.cpp#L116) because it caused a compile-time error. 
  * After this, jlnode would compile. At runtime, it errored with "Cannot create a handle without a HandleScope".
