### ISSUE TITLE
Unsatisfiable requirements

### ISSUE THREAD

**Issue by onetonfoot** [sunoru/NodeCall.jl#6]
Hey I'm trying to install but I get

```
    Updating git-repo `https://github.com/sunoru/NodeCall.jl`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libjlnode_jll [e3ef64f0]:
 libjlnode_jll [e3ef64f0] log:
 ├─possible versions are: 14.17.3 or uninstalled
 └─restricted to versions 16 by NodeCall [84d67a5e] — no versions left 
   └─NodeCall [84d67a5e] log:
     ├─possible versions are: 0.2.0 or uninstalled
     └─NodeCall [84d67a5e] is fixed to version 0.2.0
```

**Comment by sunoru** [comment]
I'm sorry. The package is still in development and the latest version is not working right now. You might check out this commit: https://github.com/sunoru/NodeCall.jl/commit/6de8905b99252dce7ce395bf8516ad845ca2152a

It uses Node v14 but there are also some bugs especially with `Promise`s.

**Comment by onetonfoot** [comment]
No worries I'll try with that commit. I hope the development goes well, solid node bindings would be a lovely addition to julia!
